services:
  - type: web
    name: parts-inventory
    runtime: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: BACKUP_EMAIL
        sync: false
